package executor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runScriptPath is the path, relative to the workspace root, where
// the wrapper script is written.
const runScriptPath = ".ai-bot/run.sh"

// scriptParams controls the wrapper script content.
type scriptParams struct {
	// Provider is the AI provider name ("claude" or "gemini").
	Provider string

	// AllowedTools is a Claude-specific space-separated list of
	// allowed tools (e.g., "Bash Edit Read Write"). Empty means
	// no restriction.
	AllowedTools string

	// Model is a Gemini-specific model override
	// (e.g., "gemini-2.5-pro"). Empty means use the default.
	Model string
}

// writeRunScript generates a provider-specific wrapper script and
// writes it to <dir>/.ai-bot/run.sh. The script invokes the AI CLI,
// captures the exit code, writes session-output.json, and exits
// with the CLI's exit code.
func writeRunScript(dir string, params scriptParams) error {
	script := generateScript(params)
	path := filepath.Join(dir, runScriptPath)

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("create script directory: %w", err)
	}

	return os.WriteFile(path, []byte(script), 0o755) // #nosec G306 -- script must be executable
}

// generateScript produces the wrapper script content for the given
// provider.
func generateScript(params scriptParams) string {
	var cmd string

	switch params.Provider {
	case "claude":
		cmd = buildClaudeCommand(params.AllowedTools)
	case "gemini":
		cmd = buildGeminiCommand(params.Model)
	default:
		// Generic fallback: assume the provider CLI accepts -p
		cmd = fmt.Sprintf("%s -p %q", params.Provider, taskPrompt)
	}

	return fmt.Sprintf(`#!/usr/bin/env bash
# AI agent wrapper script -- generated by bot, do not edit.

%s \
    2>&1 | tee /workspace/.ai-bot/session.log
AI_EXIT=${PIPESTATUS[0]}

# Write session metadata (always, even on failure).
cat > /workspace/%s <<'ENDJSON'
{"exit_code": EXITCODE_PLACEHOLDER}
ENDJSON
sed -i "s/EXITCODE_PLACEHOLDER/${AI_EXIT}/" /workspace/%s

exit ${AI_EXIT}
`, cmd, sessionOutputPath, sessionOutputPath)
}

const taskPrompt = "Read /workspace/.ai-bot/task.md and complete the task described there."

func buildClaudeCommand(allowedTools string) string {
	var parts []string
	parts = append(parts, "claude", "--dangerously-skip-permissions")

	if allowedTools != "" {
		parts = append(parts, "--allowedTools", fmt.Sprintf("%q", allowedTools))
	}

	parts = append(parts, "-p", fmt.Sprintf("%q", taskPrompt))
	return strings.Join(parts, " ")
}

func buildGeminiCommand(model string) string {
	var parts []string
	parts = append(parts, "gemini", "-y")

	if model != "" {
		parts = append(parts, "--model", fmt.Sprintf("%q", model))
	}

	parts = append(parts, "-p", fmt.Sprintf("%q", taskPrompt))
	return strings.Join(parts, " ")
}
